from typing import Protocol

from chat.application.ports.conversation_repo import ConversationRepository

# Below: Not needed if we explicitly inherit Protocols -> better for typechecking 
# #@runtime_checkable #So we can  assert isinstance(adapter, port)
class ConversationUOW(Protocol):
    #make sure that one session per unit of work
    def __enter__(self)->'ConversationUOW': ...
    def __exit__(self, exc_type, exc, tb)-> None: ...
    def commit(self): ...
    def rollback(self): ...
    @property
    def conversation_repo(self)-> ConversationRepository: ...