# frontend/Dockerfile

###############################
# Stage 1: Build the App
###############################
FROM node:23-alpine
WORKDIR /app

# Copy package management files and install dependencies
# For rebuilt optimization, this partial copy + install is done before the whole copy
COPY ./frontend/package.json .
RUN npm install

COPY frontend/ .
ENV VITE_APP_DOMAIN=${VITE_APP_DOMAIN}
ENV UPLOAD_MAX_FILE_SIZE=${UPLOAD_MAX_FILE_SIZE}
ENV UPLOAD_ALLOWED_SUFFIXES=${UPLOAD_ALLOWED_SUFFIXES}
RUN echo $UPLOAD_ALLOWED_SUFFIXES

EXPOSE 5173

CMD ["npm", "run", "dev"]