# frontend/Dockerfile

###############################
# Stage 1: Build the App
###############################
FROM node:23-alpine
WORKDIR /app

# Copy package management files and install dependencies
# For rebuilt optimization, this partial copy + install is done before the whole copy
COPY ./frontend/package.json .
RUN npm install

COPY frontend/ .

CMD ["npm", "run", "dev"]