
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-certonly
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx_lets_encrypt_setup.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-init
    depends_on:
      - nginx
    environment:
      - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    entrypoint: >
      sh -c "certbot certonly --non-interactive --webroot -w /var/www/certbot $CERTBOT_DOMAINS --email $CERTBOT_EMAIL --agree-tos --no-eff-email"
    volumes:
      - certbot_www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt



volumes:
  certbot_www:
  letsencrypt:
