services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    # Pass in environment variables from the .env file (avoid baking secrets)
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      # - loaded_images:${LOADED_IMAGES_PATH}
      # - prompt_files:${PROMPT_FILES_PATH} 
    # ports:
      # - "127.0.0.1:5678:5678"
    tty: true
    networks:
      - default
      - locust-backend-share
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5173/openapi.json"]
      interval: 60s
      timeout: 3s
      retries: 5
    
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
# Use vite prefix for envs

    environment:
      CHOKIDAR_USEPOLLING: true
      # NODE_ENV: development
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules #decouples node_module in container -> can get stale -use make target to update modules‚
      
      
    container_name: frontend
    stdin_open: true
    tty: true

  structurizr-lite:
    image: structurizr/lite:latest
    volumes:
      # your local workspace dir → where Lite expects to find workspace.dsl / workspace.json
      - ./structurizr:/usr/local/structurizr
    ports:
      - "8080:8080"
    environment:
      # make sure this matches the port exposed by the container
      - PORT=8080
    # networks: # should not be needed -test it
    #   - default
    # override entrypoint to make sure it picks up our data dir
    command: ["java", "-Djdk.util.jar.enableMultiRelease=false", "-jar", "/usr/local/structurizr-lite.war", "/usr/local/structurizr"]

  postgres:
    build:
      context: ./database/postgres
      dockerfile: Dockerfile.dev
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chat_context_db
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      CHAT_APP_PASSWORD: ${CHAT_APP_PASSWORD}
      CGPT_APP_PASSWORD: ${CGPT_APP_PASSWORD}
      CHAT_TEST_APP_PASSWORD: ${CHAT_TEST_APP_PASSWORD}
      CGPT_TEST_APP_PASSWORD: ${CGPT_TEST_APP_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql
# bind mount lead to permission problems; just copying init now works 
    # Dev only: expose to host
    ports:
      - "127.0.0.1:5432:5432"
    
    networks:
      - default

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER} -d chat_context_db"]
      interval: 5s
      timeout: 3s
      retries: 10


  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.dev
    container_name: nginx-template
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
      - structurizr-lite
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - default

volumes:
  frontend_build:
  loaded_images:
  prompt_files:
  certs:
  pgdata:
  frontend_node_modules:

networks:
  default:
  locust-backend-share:
    name: locust-backend-share
    driver: bridge