FROM python:3.13-slim

# Curl install is needed for health check
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /work/loadtests

#This will enable us to see print statements in the docker logs
ENV PYTHONUNBUFFERED=1 


# Copy the requirements file (adjust the path if needed)
COPY requirements-locust.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements-locust.txt