// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChatHistoryByIdData, ChatHistoryByIdErrors, ChatHistoryByIdResponses, CheckStatusOfDocumentData, CheckStatusOfDocumentErrors, CheckStatusOfDocumentResponses, CreateCustomGptData, CreateCustomGptErrors, CreateCustomGptResponses, DeleteCustomGptData, DeleteCustomGptErrors, DeleteCustomGptResponses, DeleteFilesData, DeleteFilesErrors, DeleteFilesResponses, EditCustomGptData, EditCustomGptErrors, EditCustomGptResponses, GetChatSummariesData, GetChatSummariesResponses, GetCustomGptInfosData, GetCustomGptInfosErrors, GetCustomGptInfosResponses, RetreiveAllCustomGptsData, RetreiveAllCustomGptsResponses, SendUserMessageData, SendUserMessageErrors, SendUserMessageResponses, UploadFilesData, UploadFilesErrors, UploadFilesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Send User Message
 */
export const sendUserMessage = <ThrowOnError extends boolean = true>(options: Options<SendUserMessageData, ThrowOnError>): RequestResult<SendUserMessageResponses, SendUserMessageErrors, ThrowOnError> => (options.client ?? client).post<SendUserMessageResponses, SendUserMessageErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chat/send-user-message',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Chat Summaries
 */
export const getChatSummaries = <ThrowOnError extends boolean = true>(options?: Options<GetChatSummariesData, ThrowOnError>): RequestResult<GetChatSummariesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetChatSummariesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chat/get-chat-summaries',
    ...options
});

/**
 * Get Chat History
 */
export const chatHistoryById = <ThrowOnError extends boolean = true>(options: Options<ChatHistoryByIdData, ThrowOnError>): RequestResult<ChatHistoryByIdResponses, ChatHistoryByIdErrors, ThrowOnError> => (options.client ?? client).get<ChatHistoryByIdResponses, ChatHistoryByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chat/chat-history-by-id',
    ...options
});

/**
 * Delete Custom Gpt Endpoint
 */
export const deleteCustomGpt = <ThrowOnError extends boolean = true>(options: Options<DeleteCustomGptData, ThrowOnError>): RequestResult<DeleteCustomGptResponses, DeleteCustomGptErrors, ThrowOnError> => (options.client ?? client).delete<DeleteCustomGptResponses, DeleteCustomGptErrors, ThrowOnError>({
    responseType: 'json',
    url: '/customgpts/delete-custom-gpt',
    ...options
});

/**
 * Create Custom Gpt
 */
export const createCustomGpt = <ThrowOnError extends boolean = true>(options: Options<CreateCustomGptData, ThrowOnError>): RequestResult<CreateCustomGptResponses, CreateCustomGptErrors, ThrowOnError> => (options.client ?? client).post<CreateCustomGptResponses, CreateCustomGptErrors, ThrowOnError>({
    responseType: 'json',
    url: '/customgpts/create-custom-gpt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Edit Custom Gpt
 */
export const editCustomGpt = <ThrowOnError extends boolean = true>(options: Options<EditCustomGptData, ThrowOnError>): RequestResult<EditCustomGptResponses, EditCustomGptErrors, ThrowOnError> => (options.client ?? client).post<EditCustomGptResponses, EditCustomGptErrors, ThrowOnError>({
    responseType: 'json',
    url: '/customgpts/edit-custom-gpt',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retreive All Custom Gpts
 */
export const retreiveAllCustomGpts = <ThrowOnError extends boolean = true>(options?: Options<RetreiveAllCustomGptsData, ThrowOnError>): RequestResult<RetreiveAllCustomGptsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<RetreiveAllCustomGptsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/customgpts/retreive-all-custom-gpts',
    ...options
});

/**
 * Get Custom Gpt By Id
 */
export const getCustomGptInfos = <ThrowOnError extends boolean = true>(options: Options<GetCustomGptInfosData, ThrowOnError>): RequestResult<GetCustomGptInfosResponses, GetCustomGptInfosErrors, ThrowOnError> => (options.client ?? client).get<GetCustomGptInfosResponses, GetCustomGptInfosErrors, ThrowOnError>({
    responseType: 'json',
    url: '/customgpts/get-custom-gpt-infos',
    ...options
});

/**
 * Delete Files Endpoint
 */
export const deleteFiles = <ThrowOnError extends boolean = true>(options: Options<DeleteFilesData, ThrowOnError>): RequestResult<DeleteFilesResponses, DeleteFilesErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFilesResponses, DeleteFilesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/knowledge/delete-files',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload File
 */
export const uploadFiles = <ThrowOnError extends boolean = true>(options: Options<UploadFilesData, ThrowOnError>): RequestResult<UploadFilesResponses, UploadFilesErrors, ThrowOnError> => (options.client ?? client).post<UploadFilesResponses, UploadFilesErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/knowledge/upload-files',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Check Status Of Document
 */
export const checkStatusOfDocument = <ThrowOnError extends boolean = true>(options: Options<CheckStatusOfDocumentData, ThrowOnError>): RequestResult<CheckStatusOfDocumentResponses, CheckStatusOfDocumentErrors, ThrowOnError> => (options.client ?? client).get<CheckStatusOfDocumentResponses, CheckStatusOfDocumentErrors, ThrowOnError>({
    responseType: 'json',
    url: '/knowledge/check_status_of_document',
    ...options
});
