// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};

/**
 * AssistantMessage
 */
export type AssistantMessage = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    response_message: SimplifiedMessageCmd;
};

/**
 * Body_uploadFiles
 */
export type BodyUploadFiles = {
    /**
     * Uploadfile
     */
    uploadFile: Blob | File;
    /**
     * Gpt Ids
     */
    gpt_ids: Array<string>;
};

/**
 * ChatHistory
 */
export type ChatHistory = {
    /**
     * Custom Gpt Id
     */
    custom_gpt_id: string | null;
    /**
     * Messages
     */
    messages: Array<SimplifiedMessageQueries>;
};

/**
 * ChatSummary
 */
export type ChatSummary = {
    /**
     * Chat Id
     */
    chat_id: string;
    /**
     * Chat Summary
     */
    chat_summary: string;
};

/**
 * CommandResult
 */
export type CommandResult = {
    /**
     * Status
     */
    status?: 'succeeded';
    /**
     * Command Id
     */
    command_id?: string | null;
    /**
     * Resource Id
     */
    resource_id?: string | null;
    /**
     * At
     */
    at?: string;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * ContinueChatRequest
 */
export type ContinueChatRequest = {
    /**
     * Request Message
     */
    request_message: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Use Rag
     */
    use_rag?: boolean;
};

/**
 * CustomGPTInfosSchema
 */
export type CustomGptInfosSchema = {
    /**
     * Custom Gpt Id
     */
    custom_gpt_id: string;
    /**
     * Custom Gpt Name
     */
    custom_gpt_name: string;
    /**
     * Custom Gpt Description
     */
    custom_gpt_description?: string | null;
    /**
     * Custom Gpt Instructions
     */
    custom_gpt_instructions: string;
};

/**
 * CustomGPTOverviewSchema
 */
export type CustomGptOverviewSchema = {
    /**
     * Custom Gpt Id
     */
    custom_gpt_id: string;
    /**
     * Custom Gpt Name
     */
    custom_gpt_name: string;
};

/**
 * CustomGptToCreate
 */
export type CustomGptToCreate = {
    /**
     * Custom Gpt Name
     */
    custom_gpt_name: string;
    /**
     * Custom Gpt Description
     */
    custom_gpt_description?: string | null;
    /**
     * Custom Gpt Instructions
     */
    custom_gpt_instructions: string;
};

/**
 * CustomGptToEdit
 */
export type CustomGptToEdit = {
    /**
     * Custom Gpt Name
     */
    custom_gpt_name: string;
    /**
     * Custom Gpt Description
     */
    custom_gpt_description?: string | null;
    /**
     * Custom Gpt Instructions
     */
    custom_gpt_instructions: string;
    /**
     * Custom Gpt Id
     */
    custom_gpt_id: string;
};

/**
 * DocumentStatusDTO
 */
export type DocumentStatusDto = 'initialized' | 'raw_document_was_stored' | 'text_extracted_but_not_chunked' | 'chunked_but_not_embedded' | 'chunks_embedded_and_ready';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NewChatRequest
 */
export type NewChatRequest = {
    /**
     * Request Message
     */
    request_message: string;
    /**
     * Custom Gpt Id
     */
    custom_gpt_id?: string | null;
    /**
     * Use Rag
     */
    use_rag?: boolean;
};

/**
 * RoleCmd
 */
export type RoleCmd = 'user' | 'assistant';

/**
 * RoleQuery
 */
export type RoleQuery = 'user' | 'assistant';

/**
 * SimplifiedMessageCmd
 */
export type SimplifiedMessageCmd = {
    role: RoleCmd;
    /**
     * Message
     */
    message: string;
};

/**
 * SimplifiedMessageQueries
 */
export type SimplifiedMessageQueries = {
    role: RoleQuery;
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SendUserMessageData = {
    /**
     * Request
     */
    body: NewChatRequest | ContinueChatRequest;
    path?: never;
    query?: never;
    url: '/chat/send-user-message';
};

export type SendUserMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendUserMessageError = SendUserMessageErrors[keyof SendUserMessageErrors];

export type SendUserMessageResponses = {
    /**
     * Successful Response
     */
    200: AssistantMessage;
};

export type SendUserMessageResponse = SendUserMessageResponses[keyof SendUserMessageResponses];

export type GetChatSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat/get-chat-summaries';
};

export type GetChatSummariesResponses = {
    /**
     * Response Getchatsummaries
     *
     * Successful Response
     */
    200: Array<ChatSummary>;
};

export type GetChatSummariesResponse = GetChatSummariesResponses[keyof GetChatSummariesResponses];

export type ChatHistoryByIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    url: '/chat/chat-history-by-id';
};

export type ChatHistoryByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatHistoryByIdError = ChatHistoryByIdErrors[keyof ChatHistoryByIdErrors];

export type ChatHistoryByIdResponses = {
    /**
     * Successful Response
     */
    200: ChatHistory;
};

export type ChatHistoryByIdResponse = ChatHistoryByIdResponses[keyof ChatHistoryByIdResponses];

export type DeleteCustomGptData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Gpt Id
         */
        gpt_id: string;
    };
    url: '/customgpts/delete-custom-gpt';
};

export type DeleteCustomGptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCustomGptError = DeleteCustomGptErrors[keyof DeleteCustomGptErrors];

export type DeleteCustomGptResponses = {
    /**
     * Successful Response
     */
    200: CommandResult;
};

export type DeleteCustomGptResponse = DeleteCustomGptResponses[keyof DeleteCustomGptResponses];

export type CreateCustomGptData = {
    body: CustomGptToCreate;
    path?: never;
    query?: never;
    url: '/customgpts/create-custom-gpt';
};

export type CreateCustomGptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCustomGptError = CreateCustomGptErrors[keyof CreateCustomGptErrors];

export type CreateCustomGptResponses = {
    /**
     * Successful Response
     */
    200: CommandResult;
};

export type CreateCustomGptResponse = CreateCustomGptResponses[keyof CreateCustomGptResponses];

export type EditCustomGptData = {
    body: CustomGptToEdit;
    path?: never;
    query?: never;
    url: '/customgpts/edit-custom-gpt';
};

export type EditCustomGptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditCustomGptError = EditCustomGptErrors[keyof EditCustomGptErrors];

export type EditCustomGptResponses = {
    /**
     * Successful Response
     */
    200: CommandResult;
};

export type EditCustomGptResponse = EditCustomGptResponses[keyof EditCustomGptResponses];

export type RetreiveAllCustomGptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/customgpts/retreive-all-custom-gpts';
};

export type RetreiveAllCustomGptsResponses = {
    /**
     * Response Retreiveallcustomgpts
     *
     * Successful Response
     */
    200: Array<CustomGptOverviewSchema>;
};

export type RetreiveAllCustomGptsResponse = RetreiveAllCustomGptsResponses[keyof RetreiveAllCustomGptsResponses];

export type GetCustomGptInfosData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Custom Gpt Id
         */
        custom_gpt_id: string;
    };
    url: '/customgpts/get-custom-gpt-infos';
};

export type GetCustomGptInfosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCustomGptInfosError = GetCustomGptInfosErrors[keyof GetCustomGptInfosErrors];

export type GetCustomGptInfosResponses = {
    /**
     * Successful Response
     */
    200: CustomGptInfosSchema;
};

export type GetCustomGptInfosResponse = GetCustomGptInfosResponses[keyof GetCustomGptInfosResponses];

export type DeleteFilesData = {
    /**
     * File Ids
     */
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/knowledge/delete-files';
};

export type DeleteFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFilesError = DeleteFilesErrors[keyof DeleteFilesErrors];

export type DeleteFilesResponses = {
    /**
     * Response Deletefiles
     *
     * Successful Response
     */
    200: Array<CommandResult>;
};

export type DeleteFilesResponse = DeleteFilesResponses[keyof DeleteFilesResponses];

export type UploadFilesData = {
    body: BodyUploadFiles;
    path?: never;
    query?: never;
    url: '/knowledge/upload-files';
};

export type UploadFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFilesError = UploadFilesErrors[keyof UploadFilesErrors];

export type UploadFilesResponses = {
    /**
     * Successful Response
     */
    200: CommandResult;
};

export type UploadFilesResponse = UploadFilesResponses[keyof UploadFilesResponses];

export type CheckStatusOfDocumentData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Cgpt Id
         */
        cgpt_id: string;
    };
    url: '/knowledge/check_status_of_document';
};

export type CheckStatusOfDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckStatusOfDocumentError = CheckStatusOfDocumentErrors[keyof CheckStatusOfDocumentErrors];

export type CheckStatusOfDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentStatusDto;
};

export type CheckStatusOfDocumentResponse = CheckStatusOfDocumentResponses[keyof CheckStatusOfDocumentResponses];
