FROM postgres:18.1

# Copy init script into the official init directory
COPY init/init.sh /docker-entrypoint-initdb.d/init.sh

# Ensure it is executable inside the image
RUN chmod +x /docker-entrypoint-initdb.d/init.sh
