FROM postgres:18.3

# Copy init script into the official init directory
COPY init/01-init-global.sh /docker-entrypoint-initdb.d/01-init-global.sh

# Ensure it is executable inside the image
RUN chmod +x /docker-entrypoint-initdb.d/*.sh
