# nginx/Dockerfile.dev
FROM nginx:stable-alpine
# Copy your custom configuration
COPY nginx_dev.conf /etc/nginx/conf.d/default.conf
COPY snippets/proxy-headers.conf /etc/nginx/snippets/proxy-headers.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
