from typing import Protocol, Sequence

from src.contexts.chat.domain.models import Conversation, ConversationOverview, Message

# Below: Not needed if we explicitly inherit Protocols -> better for typechecking 
# #@runtime_checkable #So we can  assert isinstance(adapter, port)
class ConversationRepository(Protocol):
    def get(self, conv_id:str)-> Conversation: ...
    def list_all_overviews_ordered_by_latest_msg(self,)-> Sequence[ConversationOverview]: ...
    def create_conversation(self)-> Conversation: ...
    def add_message(self, msg: Message): ...
    def delete(self, conversation: Conversation): ...


