from typing import Protocol, Sequence

from src.contexts.chat.domain.models import Conversation, ConversationOverview, Message

# Below: Not needed if we explicitly inherit Protocols -> better for typechecking 
# #@runtime_checkable #So we can  assert isinstance(adapter, port)
class ConversationRepository(Protocol):
    def get(self, conv_id:str)-> Conversation: ...
    def list_all_overviews_ordered_by_latest_msg(self,)-> Sequence[ConversationOverview]: ...
    def create_conversation(self, cgpt_id:str | None = None)-> Conversation: ...
    def delete(self, conversation: Conversation): ...
    def delete_conversations_with_cgpt(self, cgpt_id: str): ...


