from typing import Protocol, Self

from src.contexts.chat.application.ports.chat_repo import ConversationRepository


# Below: Not needed if we explicitly inherit Protocols -> better for typechecking
# #@runtime_checkable #So we can  assert isinstance(adapter, port)
class ConversationUOW(Protocol):
    # make sure that one session per unit of work
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self): ...
    def rollback(self): ...
    @property
    def conversation_repo(self) -> ConversationRepository: ...
